server:
  port: 8081
  context-path: /producer

rabbitmq:
  host: 192.168.56.105
  username: guest
  password: guest
  topicName: DEV.MESSAGE.TOPIC.MAIN
  recoveryInterval: 5000
  connectionTimeout: 10000

